// flow-typed signature: 3386105166a61d03a8c84117e4b68530
// flow-typed version: <<STUB>>/react-motion-loop_v^2.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-motion-loop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-motion-loop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-motion-loop/build/react-motion-loop' {
  declare module.exports: any;
}

declare module 'react-motion-loop/build/react-motion-loop.min' {
  declare module.exports: any;
}

declare module 'react-motion-loop/lib/Component' {
  declare module.exports: any;
}

declare module 'react-motion-loop/lib/index' {
  declare module.exports: any;
}

declare module 'react-motion-loop/src/Component' {
  declare module.exports: any;
}

declare module 'react-motion-loop/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-motion-loop/build/react-motion-loop.js' {
  declare module.exports: $Exports<'react-motion-loop/build/react-motion-loop'>;
}
declare module 'react-motion-loop/build/react-motion-loop.min.js' {
  declare module.exports: $Exports<'react-motion-loop/build/react-motion-loop.min'>;
}
declare module 'react-motion-loop/lib/Component.js' {
  declare module.exports: $Exports<'react-motion-loop/lib/Component'>;
}
declare module 'react-motion-loop/lib/index.js' {
  declare module.exports: $Exports<'react-motion-loop/lib/index'>;
}
declare module 'react-motion-loop/src/Component.js' {
  declare module.exports: $Exports<'react-motion-loop/src/Component'>;
}
declare module 'react-motion-loop/src/index.js' {
  declare module.exports: $Exports<'react-motion-loop/src/index'>;
}
