// flow-typed signature: 634462675dce1e3b0ed93904ddb996e8
// flow-typed version: <<STUB>>/react-konva_v^1.6.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-konva'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-konva' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-konva/react-konva' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-konva/react-konva.js' {
  declare module.exports: $Exports<'react-konva/react-konva'>;
}
