// flow-typed signature: d223f751f556413e6f584c47d3a0d42f
// flow-typed version: <<STUB>>/react-tween-state_v^0.1.5/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tween-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tween-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tween-state/lib/index' {
  declare module.exports: any;
}

declare module 'react-tween-state/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tween-state/lib/index.js' {
  declare module.exports: $Exports<'react-tween-state/lib/index'>;
}
declare module 'react-tween-state/webpack.config.js' {
  declare module.exports: $Exports<'react-tween-state/webpack.config'>;
}
