// flow-typed signature: f49e4612baf7fa5f80247689322bb96a
// flow-typed version: <<STUB>>/react-move_v^2.6.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-move'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-move' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-move/Animate/Animate' {
  declare module.exports: any;
}

declare module 'react-move/Animate/index' {
  declare module.exports: any;
}

declare module 'react-move/core/mergeKeys' {
  declare module.exports: any;
}

declare module 'react-move/core/transition/index' {
  declare module.exports: any;
}

declare module 'react-move/core/transition/schedule' {
  declare module.exports: any;
}

declare module 'react-move/core/transition/stop' {
  declare module.exports: any;
}

declare module 'react-move/core/transition/transition' {
  declare module.exports: any;
}

declare module 'react-move/core/transition/tween' {
  declare module.exports: any;
}

declare module 'react-move/core/types' {
  declare module.exports: any;
}

declare module 'react-move/dist/react-move' {
  declare module.exports: any;
}

declare module 'react-move/dist/react-move.min' {
  declare module.exports: any;
}

declare module 'react-move/index.es' {
  declare module.exports: any;
}

declare module 'react-move/Node/index' {
  declare module.exports: any;
}

declare module 'react-move/Node/Node' {
  declare module.exports: any;
}

declare module 'react-move/NodeGroup/index' {
  declare module.exports: any;
}

declare module 'react-move/NodeGroup/NodeGroup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-move/Animate/Animate.js' {
  declare module.exports: $Exports<'react-move/Animate/Animate'>;
}
declare module 'react-move/Animate/index.js' {
  declare module.exports: $Exports<'react-move/Animate/index'>;
}
declare module 'react-move/core/mergeKeys.js' {
  declare module.exports: $Exports<'react-move/core/mergeKeys'>;
}
declare module 'react-move/core/transition/index.js' {
  declare module.exports: $Exports<'react-move/core/transition/index'>;
}
declare module 'react-move/core/transition/schedule.js' {
  declare module.exports: $Exports<'react-move/core/transition/schedule'>;
}
declare module 'react-move/core/transition/stop.js' {
  declare module.exports: $Exports<'react-move/core/transition/stop'>;
}
declare module 'react-move/core/transition/transition.js' {
  declare module.exports: $Exports<'react-move/core/transition/transition'>;
}
declare module 'react-move/core/transition/tween.js' {
  declare module.exports: $Exports<'react-move/core/transition/tween'>;
}
declare module 'react-move/core/types.js' {
  declare module.exports: $Exports<'react-move/core/types'>;
}
declare module 'react-move/dist/react-move.js' {
  declare module.exports: $Exports<'react-move/dist/react-move'>;
}
declare module 'react-move/dist/react-move.min.js' {
  declare module.exports: $Exports<'react-move/dist/react-move.min'>;
}
declare module 'react-move/index.es.js' {
  declare module.exports: $Exports<'react-move/index.es'>;
}
declare module 'react-move/index' {
  declare module.exports: $Exports<'react-move'>;
}
declare module 'react-move/index.js' {
  declare module.exports: $Exports<'react-move'>;
}
declare module 'react-move/Node/index.js' {
  declare module.exports: $Exports<'react-move/Node/index'>;
}
declare module 'react-move/Node/Node.js' {
  declare module.exports: $Exports<'react-move/Node/Node'>;
}
declare module 'react-move/NodeGroup/index.js' {
  declare module.exports: $Exports<'react-move/NodeGroup/index'>;
}
declare module 'react-move/NodeGroup/NodeGroup.js' {
  declare module.exports: $Exports<'react-move/NodeGroup/NodeGroup'>;
}
